# 6.3 실습 - 인공신경망 학습

## 6.3.1 인공신경망 학습하기 - 기본

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns #기능<미

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
tf.__version__

'2.10.0'

In [3]:
# 데이터 불러오기
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['label'] = iris.target

In [4]:
# 데이터분할
y = df['label']
X = df.drop(['label'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

In [5]:
X_train.shape

(112, 4)

In [7]:
# 모델의 설정
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu')) # 은닉
model.add(Dense(3, activation='softmax')) # 출력

In [8]:
# 모델 컴파일
model.compile(loss='sparse_categorical_crossentropy',
            optimizer='adam',
            metrics=['accuracy'])

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 3)                 27        
                                                                 
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [10]:
# 모델 실행
model.fit(X_train, y_train, epochs=50, batch_size=4)

Epoch 1/50
28/28 [==============================] - 2s 1ms/step - loss: 1.7080 - accuracy: 0.3304  
Epoch 2/50
28/28 [==============================] - 0s 1ms/step - loss: 1.3825 - accuracy: 0.3304
Epoch 3/50
28/28 [==============================] - 0s 2ms/step - loss: 1.2550 - accuracy: 0.2946
Epoch 4/50
28/28 [==============================] - 0s 1ms/step - loss: 1.2135 - accuracy: 0.2232
Epoch 5/50
28/28 [==============================] - 0s 1ms/step - loss: 1.1854 - accuracy: 0.1696
Epoch 6/50
28/28 [==============================] - 0s 2ms/step - loss: 1.1501 - accuracy: 0.2857
Epoch 7/50
28/28 [==============================] - 0s 1ms/step - loss: 1.1170 - accuracy: 0.3304
Epoch 8/50
28/28 [==============================] - 0s 1ms/step - loss: 1.0876 - accuracy: 0.3929
Epoch 9/50
28/28 [==============================] - 0s 2ms/step - loss: 1.0619 - accuracy: 0.4554
Epoch 10/50
28/28 [==============================] - 0s 1ms/step - loss: 1.0427 - accuracy: 0.4375
Epoch 11/50
28/28

In [11]:
model.evaluate(X_test, y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.5287 - accuracy: 0.8421


[0.5286850929260254, 0.8421052694320679]

In [12]:
model.predict(X_test)[0]

2/2 [==============================] - 0s 4ms/step


array([0.6516344 , 0.24257477, 0.1057908 ], dtype=float32)

In [13]:
# 테스트 데이터로 예측한 값이 가장 큰 값을 반환(argmax)한 결과
np.argmax(model.predict(X_test)[0])

2/2 [==============================] - 0s 4ms/step


0

In [14]:
# 테스트셋의 실제값
y_test.iloc[0]

0

### 전체 소스 코드

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# 데이터 불러오기
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['label'] = iris.target

# 데이터분할
y = df['label']
X = df.drop(['label'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y)

# 모델의 설정
model = Sequential()
model.add(Dense(8, input_dim=4, activation='softmax'))
model.add(Dense(3, activation='softmax'))

# 모델 컴파일
model.compile(loss='sparse_categorical_crossentropy',
            optimizer='SGD',
            metrics=['accuracy'])

# history = model.fit(X_train,y_target,epochs=20,verbose=0, validation_data=(val)
# 모델 실행
model.fit(X_train, y_train, epochs=50, batch_size=4)

# 모델 평가
model.evaluate(X_test, y_test)

# 값 예측
model.predict(X_test)[0]

Epoch 1/50
28/28 [==============================] - 0s 1ms/step - loss: 1.0689 - accuracy: 0.3482
Epoch 2/50
28/28 [==============================] - 0s 1ms/step - loss: 1.0435 - accuracy: 0.3393
Epoch 3/50
28/28 [==============================] - 0s 1ms/step - loss: 1.0198 - accuracy: 0.7143
Epoch 4/50
28/28 [==============================] - 0s 1ms/step - loss: 0.9980 - accuracy: 0.8125
Epoch 5/50
28/28 [==============================] - 0s 1ms/step - loss: 0.9778 - accuracy: 0.7143
Epoch 6/50
28/28 [==============================] - 0s 1ms/step - loss: 0.9569 - accuracy: 0.8571
Epoch 7/50
28/28 [==============================] - 0s 2ms/step - loss: 0.9381 - accuracy: 0.6875
Epoch 8/50
28/28 [==============================] - 0s 995us/step - loss: 0.9183 - accuracy: 0.7500
Epoch 9/50
28/28 [==============================] - 0s 2ms/step - loss: 0.8994 - accuracy: 0.6696
Epoch 10/50
28/28 [==============================] - 0s 1ms/step - loss: 0.8811 - accuracy: 0.6786
Epoch 11/50
28/28

array([0.820585  , 0.11579648, 0.06361847], dtype=float32)

In [16]:
model.predict(X_test)[0]

2/2 [==============================] - 0s 5ms/step


array([0.9469274 , 0.05093049, 0.00214204], dtype=float32)